### ISSUE TITLE
JWTの有効期限がハードコーディングされている

### ISSUE THREAD

**Issue by averak** [averak/rippy#8]
有効期限をプロファイルから指定できるようにする。

有効期限を一週間にする場合は下記のようになる。

```yaml
jwt:
  secret: ...
  issuer: ...
  expiry: 7 * 24 * 60 * 60 * 1000
```
